version: '3.9'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SuperAdm1n!
      - TZ=Europe/Oslo
    ports:
      - "1433:1433"